
name: Deploy
on:
  push:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - run: nix-build -A dockerImage.tarball

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    concurrency: deploy
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - run: eval $(nix-build -A deployScript)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
